export {default as Following} from './Following'
export {default as Home} from './Home'
export {default as Profile} from './Profile'
export {default as Register} from './Register'
export {default as Login} from './Login'